-- MySQL Script generated by MySQL Workbench
-- 09/24/15 20:33:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ShoppingCart
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ShoppingCart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ShoppingCart` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ShoppingCart` ;

-- -----------------------------------------------------
-- Table `ShoppingCart`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoppingCart`.`Categories` (
  `Id` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoppingCart`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoppingCart`.`Products` (
  `Id` INT PRIMARY KEY AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Quantity` INT NOT NULL,
  `Price` DECIMAL NOT NULL,
  `Category_Id` INT NOT NULL,
  INDEX `fk_Products_Categories_idx` (`Category_Id` ASC),
  CONSTRAINT `fk_Products_Categories`
    FOREIGN KEY (`Category_Id`)
    REFERENCES `ShoppingCart`.`Categories` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoppingCart`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoppingCart`.`Users` (
  `Id` INT PRIMARY KEY AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Balance` DECIMAL NOT NULL,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ShoppingCart`.`Users_has_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ShoppingCart`.`Users_has_Products` (
  `User_Id` INT NOT NULL,
  `Product_Id` INT NOT NULL,
  PRIMARY KEY (`User_Id`, `Product_Id`),
  INDEX `fk_Users_has_Products_Products1_idx` (`Product_Id` ASC),
  INDEX `fk_Users_has_Products_Users1_idx` (`User_Id` ASC),
  CONSTRAINT `fk_Users_has_Products_Users1`
    FOREIGN KEY (`User_Id`)
    REFERENCES `ShoppingCart`.`Users` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Products_Products1`
    FOREIGN KEY (`Product_Id`)
    REFERENCES `ShoppingCart`.`Products` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
